# 01-DEPT.sql

```sql
-- DDL for DEPT

CREATE TABLE DEPT
(
    DEPT_ID NUMBER(4),
    DEPT_NAME VARCHAR2(100) NOT NULL,
    MANAGER_ID NUMBER(5),
    LOC_ID NUMBER(5),
    CONSTRAINT DEPRT_ID_PK PRIMARY KEY (DEPT_ID)
);


-- INSERTING DATA INTO DEPT

INSERT INTO DEPT (DEPT_ID, DEPT_NAME, MANAGER_ID, LOC_ID)
VALUES (20, 'Admin', 300, 2100);

INSERT INTO DEPT (DEPT_ID, DEPT_NAME, MANAGER_ID, LOC_ID)
VALUES (21, 'Marketing', 301, 2200);

INSERT INTO DEPT (DEPT_ID, DEPT_NAME, MANAGER_ID, LOC_ID)
VALUES (22, 'Shipping', 302, 2300);

INSERT INTO DEPT (DEPT_ID, DEPT_NAME, MANAGER_ID, LOC_ID)
VALUES (23, 'IT', 303, 2400);

INSERT INTO DEPT (DEPT_ID, DEPT_NAME, MANAGER_ID, LOC_ID)
VALUES (24, 'Sales', 304, 2500);

INSERT INTO DEPT (DEPT_ID, DEPT_NAME, MANAGER_ID, LOC_ID)
VALUES (25, 'Executive', 305, 2600);

INSERT INTO DEPT (DEPT_ID, DEPT_NAME, MANAGER_ID, LOC_ID)
VALUES (110, 'Acc', 306, 2700);

INSERT INTO DEPT (DEPT_ID, DEPT_NAME, LOC_ID)
VALUES (190, 'Contracting', 2800);

INSERT INTO DEPT (DEPT_ID, DEPT_NAME, MANAGER_ID, LOC_ID)
VALUES (26, 'Admin', 307, 2900);
```

This contains the **DEPT table creation + all DEPT data** used for the subsequent queries. The DEPT data shown in the material is: IDs 20, 21, 22, 23, 24, 25, 110, 190, and 26. 
